services:
  - type: web
    name: bett-app
    runtime: python
    buildCommand: "bash build.sh"
    startCommand: "gunicorn mymainserver.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.14.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: bett-db
          property: connectionString
